language: node_js

node_js:
  - stable

cache:
  directories:
    - node_modules

script:
  - npm run build

before_deploy:
  - export RELEASE_VERSION=$(git --no-pager describe --tags --always)
  - tar czf ticker-admin-$RELEASE_VERSION.tar.gz -C dist/ .
  - shasum -a 512 ticker-admin-$RELEASE_VERSION.tar.gz > sha512sums.txt

deploy:
  provider: releases
  api_key:
    secure: "m4y/mermiTqkjH95NjhvENfqKpxFBWVq7AV07kw1iMfjZoLjrSSQ5oDv/4s2NmxTBnsvoj+nPGw8NcRW57Jrea772nwRdkmBDlnRnaLFZJ3iU/FJvbk71riTUMj2HvDYqi4ITxSJM0HyeSWSPMU4ZAKU+sZQBZ7XBUOy4KmJTgL2OxDblSWMwL93j6Y0fhwp6rwRqexEaTT7dr0VkD9WFjUw4HKdTBS2Z5fpP+Y7uaP9Nu9ydTneGaMIImVJ/NekNpfOiNTUApjmYys20h0ICam8epG8pFsgv8A0uHzKYF6lH+6KndIdeTN6xDvXPcXRTPOHs2g88c9YWMZ5jUt1/MbKXbfuqBvSJWvQhbEw25UIKQbVYJ7kVVCf9PjZMkhmhkY/ksgoZVcTcBslNTXqSx2yL47kjMrSrc0eUiW/o7eldqf1qEVPlvSDF4sBWny89IvO6+/dSrPAbwUp2joeh2K2V0lPjZURGwbkMOcqwNq1xGu0wMduVLxY2AMOyBM5SrfQIYBaDM2hQV0XDJxmgU4P3hpTtv0qkqjQXigVlEY9CDPb5LOf5h0yVXik/6DWougKrI3owQblWwWLKR3LJei1T86Ev3ea+yTHArVr9L7goaa3WWWJUlWGBdjxC+2ceeVC8jzGSbDfl8n2ELHmn9YarWV9NQTjWjVB+kg1x38="
  file:
    - ticker-admin-$RELEASE_VERSION.tar.gz
    - sha512sums.txt
  skip_cleanup: true
  on:
    repo: systemli/ticker-admin
    tags: true
