language: node_js

node_js:
  - stable

cache:
  directories:
    - node_modules

script:
  - npm run build

before_deploy:
  - export RELEASE_VERSION=$(git --no-pager describe --tags --always)
  - tar czf ticker-admin-$RELEASE_VERSION.tar.gz -C dist/ .
  - shasum -a 512 ticker-admin-$RELEASE_VERSION.tar.gz > sha512sums.txt

deploy:
  provider: releases
  api_key:
    secure: IcpALEvWHjGp3HzDlqpngfLaLfkx2Cz4Ei2TKtcBBNz/S+8+YQN/FnAHK+JZA8Py33ft5JjkQks0jXoLRWCHLyVlGyGtC6mkDGXSWqUWO7CsMENmwqCDMY49mOjSq5kkML+O/tVzH/TpEFbJqIVEiYZpf0fxPJQ+NcHSEdqqqjXRrTKUvwkpSzbk3fFJsNzdz77ItRBpQtq6mF83jfPNLmd8E/sCYImpzy3qLvz608DuRLdk1/JM+w9BTpu/vFk3BEtlmM2Ibtq72OhAyX7Ws4Oi+9to2ygC1iP0yzHuoYHC0uWHqbY3iw4vv6vVx5xJRUR3l3OPUIRPpdS5ccv8H/qgDRObNkgXZTDc6x438vg09u+4lYKZ3OJNWVLzJwTq+6FWYpVBnJA4FNglnBrE4wfUyonAdZ8+MClFjfuh28T2qnPB/H12CBRyjZd1EJUWa6VBcwe4RtDoKG6KZnY8n1SGFfd2+Wf8WgRvsWsfbQA0vSaGlrBANEKmrL9SBXSu4fqod64r8eLBPUg7uLooUTXxtSpmOn2C3vEs2XKfBes4XkcvphfybuQn3B1aMvd3KdB8VtiN6R64ZkdK4VOh+dvG8K3VqLcFw7U8u4awR78SvwmjVxL0+lY8Guu9pXnW3FYAyW34H2M9WtdK8JwbYw1Z5lw1VT1KrFB8iqzb+qo=
  file:
    - ticker-admin-$RELEASE_VERSION.tar.gz
    - sha512sums.txt
  skip_cleanup: true
  on:
    repo: systemli/ticker-admin
    tags: true
